/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bank_management_system.Loans;

import com.mycompany.bank_management_system.Employee;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed Ahmed
 */
public class LoanApplicationFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoanApplicationFrame
     */
    public LoanApplicationFrame() {
        initComponents();
        Calendar startDate = Calendar.getInstance();
        startDate.setTime(startDateChooser.getDate());
        Date endDate = new Date();
        loans.setStartDate(startDateChooser.getDate());
        startDate.add(Calendar.MONTH, 3);
        endDate = startDate.getTime();
        loans.setEndDate(endDate);
    }
    
    private LoanDBManager loans = new LoanDBManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        startDateLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        durationLabel = new javax.swing.JLabel();
        durationComboBox = new javax.swing.JComboBox<>();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        interestRateLabel = new javax.swing.JLabel();
        interestRateField = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(4, 72, 92));

        jPanel5.setBackground(new java.awt.Color(4, 72, 92));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Loan Application", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        startDateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        startDateLabel.setText("Start Date:");

        idField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 51, 0));
        backButton.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.setPreferredSize(new java.awt.Dimension(149, 30));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("Customer ID:");

        Calendar nextMonth = Calendar.getInstance();
        nextMonth.add(Calendar.MONTH, 1);
        nextMonth.set(Calendar.DAY_OF_MONTH, 1);
        startDateChooser.setMinSelectableDate(nextMonth.getTime());
        startDateChooser.setCalendar(nextMonth);

        durationLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(255, 255, 255));
        durationLabel.setText("Duration:");

        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 Months", "6 Months", "1 Year", "2 Years", "3 Years", "5 Years", "10 Years", "15 Years" }));
        durationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationComboBoxActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel.setText("Amount:");

        amountField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        amountField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        interestRateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        interestRateLabel.setForeground(new java.awt.Color(255, 255, 255));
        interestRateLabel.setText("Interest Rate:");

        interestRateField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        interestRateField.setForeground(new java.awt.Color(0, 153, 0));
        interestRateField.setText("0.02");
        interestRateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        interestRateField.setFocusable(false);
        interestRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRateFieldActionPerformed(evt);
            }
        });

        applyButton.setBackground(new java.awt.Color(0, 105, 139));
        applyButton.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        applyButton.setForeground(new java.awt.Color(255, 255, 255));
        applyButton.setText("Apply");
        applyButton.setFocusable(false);
        applyButton.setPreferredSize(new java.awt.Dimension(149, 30));
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(idLabel)
                            .addGap(18, 18, 18)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(startDateLabel)
                            .addGap(18, 18, 18)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(durationLabel)
                            .addGap(18, 18, 18)
                            .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(amountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interestRateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 410, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed

    }//GEN-LAST:event_idFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new Employee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void interestRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestRateFieldActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        boolean valid = true;
        int customerID = 0;
        try{
            customerID = Integer.parseInt(idField.getText());
            if(loans.isCustomerIDValid(customerID)){
                loans.setCustomerID(customerID);
            }else{
                JOptionPane.showMessageDialog(null, "Customer ID not Found!", "Warning", JOptionPane.WARNING_MESSAGE);
                valid = false;
            }
        }catch(NumberFormatException e){
            //show jOptionPane with error message
            JOptionPane.showMessageDialog(null, "Please Enter a valid Cutomer ID!", "Warning", JOptionPane.WARNING_MESSAGE);
            valid = false;
        }
        
        if (loans.isValidAmount(amountField)){
            double amount = Double.parseDouble(amountField.getText());
            loans.setAmount(amount);
        }else{
            //show jOptionPane with error message
            JOptionPane.showMessageDialog(null, "Please Enter a valid amount!", "Warning", JOptionPane.WARNING_MESSAGE);
            valid = false;
        }
        // if amount and Customer ID is valid aplly for the loan
        if(valid){
            System.out.println("Valid loan application");
            double interestRate = Double.parseDouble(interestRateField.getText());
            loans.setInterestRate(interestRate);
            loans.applyForLoan();
            JOptionPane.showMessageDialog(null, "You have successfully applied for a Loan!");
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void durationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationComboBoxActionPerformed
        String duration = (String) durationComboBox.getSelectedItem();
        Calendar startDate = Calendar.getInstance();
        startDate.setTime(startDateChooser.getDate());
        Date endDate = new Date();
        double interestRate = 0.0;
        // Determine interest rate based on selected loan duration
        switch (duration) {
            case "3 Months" -> {
                interestRate = 0.02;
                startDate.add(Calendar.MONTH, 3);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            } // 2%
            case "6 Months" -> {
                interestRate = 0.025; // 2.5%
                startDate.add(Calendar.MONTH, 6);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "1 Year" -> {
                interestRate = 0.03; // 3%
                startDate.add(Calendar.YEAR, 1);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "2 Years" -> {
                interestRate = 0.035; // 3.5%
                startDate.add(Calendar.YEAR, 2);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "3 Years" -> {
                interestRate = 0.04; // 4%
                startDate.add(Calendar.YEAR, 3);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "5 Years" -> {
                interestRate = 0.045; // 4.5%
                startDate.add(Calendar.YEAR, 5);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "10 Years" -> {
                interestRate = 0.05; // 5%
                startDate.add(Calendar.YEAR, 10);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
            case "15 Years" -> {
                interestRate = 0.055; // 5.5%
                startDate.add(Calendar.YEAR, 15);
                endDate = startDate.getTime();
                loans.setStartDate(startDateChooser.getDate());
                loans.setEndDate(endDate);
            }
        }
        interestRateField.setText(String.valueOf(interestRate));
    }//GEN-LAST:event_durationComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanApplicationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> durationComboBox;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField interestRateField;
    private javax.swing.JLabel interestRateLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration//GEN-END:variables
}
