/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm_app.FundsTransfer;

import com.mycompany.atm_app.Main;
import static com.mycompany.atm_app.FundsTransfer.TargetAccountFrame.fundsTransferFun;
import javax.swing.JOptionPane;
/**
 *
 * @author Mohamed Ahmed
 */
public class AccountNumberTransferFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountNumberFrame
     */
    public AccountNumberTransferFrame() {
        initComponents();
        fundsTransferFun.setCharLimit(11);
        amountTextbox.setText(fundsTransferFun.getTransferAmount());
        targetTextbox.setText(fundsTransferFun.getTargetAccNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        amountTextbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phoneNumTextbox = new javax.swing.JTextField();
        numPad7 = new javax.swing.JButton();
        numPad8 = new javax.swing.JButton();
        numPad9 = new javax.swing.JButton();
        numPad6 = new javax.swing.JButton();
        numPad5 = new javax.swing.JButton();
        numPad4 = new javax.swing.JButton();
        numPad1 = new javax.swing.JButton();
        numPad2 = new javax.swing.JButton();
        numPad3 = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        numPad0 = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        targetTextbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBackground(new java.awt.Color(255, 0, 0));
        BackButton.setFont(BackButton.getFont().deriveFont(BackButton.getFont().getStyle() | java.awt.Font.BOLD, BackButton.getFont().getSize()+2));
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.setToolTipText("");
        BackButton.setFocusPainted(false);
        BackButton.setFocusable(false);
        BackButton.setPreferredSize(new java.awt.Dimension(150, 35));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 160, 40));

        amountTextbox.setBackground(new java.awt.Color(102, 102, 102));
        amountTextbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amountTextbox.setForeground(new java.awt.Color(0, 204, 0));
        amountTextbox.setFocusable(false);
        amountTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(amountTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("EGP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 300, 40, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Enter your phone number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        phoneNumTextbox.setBackground(new java.awt.Color(102, 102, 102));
        phoneNumTextbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phoneNumTextbox.setForeground(new java.awt.Color(0, 204, 0));
        phoneNumTextbox.setFocusable(false);
        phoneNumTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 220, 30));

        numPad7.setBackground(new java.awt.Color(102, 102, 102));
        numPad7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad7.setText("7");
        numPad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad7ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 110, 70));

        numPad8.setBackground(new java.awt.Color(102, 102, 102));
        numPad8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad8.setText("8");
        numPad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad8ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 110, 70));

        numPad9.setBackground(new java.awt.Color(102, 102, 102));
        numPad9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad9.setText("9");
        numPad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad9ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 110, 70));

        numPad6.setBackground(new java.awt.Color(102, 102, 102));
        numPad6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad6.setText("6");
        numPad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad6ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 110, 70));

        numPad5.setBackground(new java.awt.Color(102, 102, 102));
        numPad5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad5.setText("5");
        numPad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad5ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 110, 70));

        numPad4.setBackground(new java.awt.Color(102, 102, 102));
        numPad4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad4.setText("4");
        numPad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad4ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 110, 70));

        numPad1.setBackground(new java.awt.Color(102, 102, 102));
        numPad1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad1.setText("1");
        numPad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad1ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 110, 70));

        numPad2.setBackground(new java.awt.Color(102, 102, 102));
        numPad2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad2.setText("2");
        numPad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad2ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 110, 70));

        numPad3.setBackground(new java.awt.Color(102, 102, 102));
        numPad3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad3.setText("3");
        numPad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad3ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 110, 70));

        transferButton.setBackground(new java.awt.Color(102, 204, 0));
        transferButton.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        transferButton.setForeground(new java.awt.Color(51, 51, 51));
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 110, 70));

        numPad0.setBackground(new java.awt.Color(102, 102, 102));
        numPad0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad0.setText("0");
        numPad0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad0ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad0, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, 110, 70));

        backspaceButton.setBackground(new java.awt.Color(255, 0, 0));
        backspaceButton.setFont(backspaceButton.getFont().deriveFont(backspaceButton.getFont().getStyle() | java.awt.Font.BOLD, 60));
        backspaceButton.setIcon(new javax.swing.ImageIcon("ICONS/icons8-clear-symbol-100.png"));
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backspaceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 110, 70));

        targetTextbox.setBackground(new java.awt.Color(102, 102, 102));
        targetTextbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        targetTextbox.setForeground(new java.awt.Color(0, 204, 0));
        targetTextbox.setFocusable(false);
        targetTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(targetTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Target Account:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Amount:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("ICONS/ATM.JPG"));
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new CashTransferFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void amountTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextboxActionPerformed

    }//GEN-LAST:event_amountTextboxActionPerformed

    private void phoneNumTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumTextboxActionPerformed

    private void numPad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad7ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "7");
    }//GEN-LAST:event_numPad7ActionPerformed

    private void numPad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad8ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "8");
    }//GEN-LAST:event_numPad8ActionPerformed

    private void numPad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad9ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "9");
    }//GEN-LAST:event_numPad9ActionPerformed

    private void numPad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad6ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "6");
    }//GEN-LAST:event_numPad6ActionPerformed

    private void numPad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad5ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "5");
    }//GEN-LAST:event_numPad5ActionPerformed

    private void numPad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad4ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "4");
    }//GEN-LAST:event_numPad4ActionPerformed

    private void numPad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad1ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "1");
    }//GEN-LAST:event_numPad1ActionPerformed

    private void numPad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad2ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "2");
    }//GEN-LAST:event_numPad2ActionPerformed

    private void numPad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad3ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "3");
    }//GEN-LAST:event_numPad3ActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        String amount = fundsTransferFun.getTransferAmount();
        String contactNum = fundsTransferFun.getContactNumber();
        if(contactNum.equals(phoneNumTextbox.getText())){
            int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to Transfer " + amount + "EGP?", "Confirmation", JOptionPane.YES_NO_OPTION);
            // Checking the user's choice
            if (choice == JOptionPane.YES_OPTION) {
                System.out.println("User confirmed.");
                // print reciept
                fundsTransferFun.insertTransferProcess();
                JOptionPane.showMessageDialog(null, "You have successfully Transfered " + amount + " EGP!", "Success", JOptionPane.INFORMATION_MESSAGE);
                new Main().setVisible(true);
                this.dispose();
            } else {
                System.out.println("User canceled.");
                // cancel withdrawl
            }
        }else{
            JOptionPane.showMessageDialog(null, "Phone number is Incorrect!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_transferButtonActionPerformed

    private void numPad0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad0ActionPerformed
        if(phoneNumTextbox.getText().length()< fundsTransferFun.getCharLimit())
        phoneNumTextbox.setText(phoneNumTextbox.getText() + "0");
    }//GEN-LAST:event_numPad0ActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        String currentText = phoneNumTextbox.getText();
        if(currentText.length()>0){
            currentText = currentText.substring(0, currentText.length()-1);
            phoneNumTextbox.setText(currentText);}
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void targetTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetTextboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountNumberTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountNumberTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountNumberTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountNumberTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountNumberTransferFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField amountTextbox;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton numPad0;
    private javax.swing.JButton numPad1;
    private javax.swing.JButton numPad2;
    private javax.swing.JButton numPad3;
    private javax.swing.JButton numPad4;
    private javax.swing.JButton numPad5;
    private javax.swing.JButton numPad6;
    private javax.swing.JButton numPad7;
    private javax.swing.JButton numPad8;
    private javax.swing.JButton numPad9;
    private javax.swing.JTextField phoneNumTextbox;
    private javax.swing.JTextField targetTextbox;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
