/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm_app.Withdraw;

import static ATM.LogIn.accNumber;
import com.mycompany.atm_app.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed Ahmed
 */
public class WithdrawFrame extends javax.swing.JFrame {

    /**
     * Creates new form CashWithdrawal
     */
    public WithdrawFrame() {
        initComponents();
        WithdrawFun.setAccNum(accNumber);
        WithdrawFun.loadVariables();
        WithdrawFun.setMaxLimit();
        jLabel3.setText("*Maximum Withdraw amount = " + WithdrawFun.getMaxValue());
        
    }
    static WithdrawFunctions WithdrawFun = new WithdrawFunctions(11);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        withdrawTextbox = new javax.swing.JTextField();
        numPad8 = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        numPad7 = new javax.swing.JButton();
        numPad9 = new javax.swing.JButton();
        numPad4 = new javax.swing.JButton();
        numPad5 = new javax.swing.JButton();
        numPad6 = new javax.swing.JButton();
        numPad1 = new javax.swing.JButton();
        numPad2 = new javax.swing.JButton();
        numPad3 = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        numPad00 = new javax.swing.JButton();
        numPad000 = new javax.swing.JButton();
        numPad0 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBackground(new java.awt.Color(255, 0, 0));
        BackButton.setFont(BackButton.getFont().deriveFont(BackButton.getFont().getStyle() | java.awt.Font.BOLD, BackButton.getFont().getSize()+2));
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.setToolTipText("");
        BackButton.setFocusPainted(false);
        BackButton.setFocusable(false);
        BackButton.setPreferredSize(new java.awt.Dimension(150, 35));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 160, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Enter the amount:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        withdrawTextbox.setBackground(new java.awt.Color(102, 102, 102));
        withdrawTextbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        withdrawTextbox.setForeground(new java.awt.Color(0, 204, 0));
        withdrawTextbox.setFocusable(false);
        withdrawTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 200, 30));

        numPad8.setBackground(new java.awt.Color(102, 102, 102));
        numPad8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad8.setText("8");
        numPad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad8ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 110, 50));

        withdrawButton.setBackground(new java.awt.Color(102, 204, 0));
        withdrawButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        withdrawButton.setForeground(new java.awt.Color(51, 51, 51));
        withdrawButton.setText("Continue");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 220, 70));

        numPad7.setBackground(new java.awt.Color(102, 102, 102));
        numPad7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad7.setText("7");
        numPad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad7ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 50));

        numPad9.setBackground(new java.awt.Color(102, 102, 102));
        numPad9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad9.setText("9");
        numPad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad9ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 110, 50));

        numPad4.setBackground(new java.awt.Color(102, 102, 102));
        numPad4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad4.setText("4");
        numPad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad4ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 50));

        numPad5.setBackground(new java.awt.Color(102, 102, 102));
        numPad5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad5.setText("5");
        numPad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad5ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 110, 50));

        numPad6.setBackground(new java.awt.Color(102, 102, 102));
        numPad6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad6.setText("6");
        numPad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad6ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 110, 50));

        numPad1.setBackground(new java.awt.Color(102, 102, 102));
        numPad1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad1.setText("1");
        numPad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad1ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 110, 50));

        numPad2.setBackground(new java.awt.Color(102, 102, 102));
        numPad2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad2.setText("2");
        numPad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad2ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 110, 50));

        numPad3.setBackground(new java.awt.Color(102, 102, 102));
        numPad3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad3.setText("3");
        numPad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad3ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 110, 50));

        backspaceButton.setBackground(new java.awt.Color(255, 0, 0));
        backspaceButton.setFont(backspaceButton.getFont().deriveFont(backspaceButton.getFont().getStyle() | java.awt.Font.BOLD, 60));
        backspaceButton.setIcon(new javax.swing.ImageIcon("ICONS/icons8-clear-symbol-100.png"));
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backspaceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 190, 70));

        numPad00.setBackground(new java.awt.Color(102, 102, 102));
        numPad00.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad00.setText("00");
        numPad00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad00ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad00, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 110, 50));

        numPad000.setBackground(new java.awt.Color(102, 102, 102));
        numPad000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad000.setText("000");
        numPad000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad000ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad000, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 110, 50));

        numPad0.setBackground(new java.awt.Color(102, 102, 102));
        numPad0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numPad0.setText("0");
        numPad0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPad0ActionPerformed(evt);
            }
        });
        getContentPane().add(numPad0, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 110, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Maximum Withdraw amount = ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("EGP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("ICONS/ATM.JPG"));
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void withdrawTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawTextboxActionPerformed

    }//GEN-LAST:event_withdrawTextboxActionPerformed

    private void numPad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad8ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "8");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad8ActionPerformed

    private void numPad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad7ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "7");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad7ActionPerformed

    private void numPad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad9ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "9");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad9ActionPerformed

    private void numPad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad4ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "4");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad4ActionPerformed

    private void numPad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad5ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "5");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad5ActionPerformed

    private void numPad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad6ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "6");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad6ActionPerformed

    private void numPad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad1ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "1");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad1ActionPerformed

    private void numPad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad2ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "2");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad2ActionPerformed

    private void numPad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad3ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "3");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad3ActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        String currentText = withdrawTextbox.getText();
        if(currentText.length()>0){
            currentText = currentText.substring(0, currentText.length()-1);
            withdrawTextbox.setText(currentText);}
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void numPad00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad00ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "00");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad00ActionPerformed

    private void numPad000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad000ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "000");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad000ActionPerformed

    private void numPad0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPad0ActionPerformed
        withdrawTextbox.setText(withdrawTextbox.getText() + "0");
        WithdrawFun.CheckAndUpdate(withdrawTextbox);
    }//GEN-LAST:event_numPad0ActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        switch(WithdrawFun.isValidAmount(withdrawTextbox)){
            case 1:
                WithdrawFun.setWithdrawAmount(withdrawTextbox.getText());
                new AccountNumberWithdrawFrame().setVisible(true);
                this.dispose();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Please Enter a valid widthdrawl amount!", "Warning", JOptionPane.WARNING_MESSAGE);
                withdrawTextbox.setText("");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Minimum Withdraw amount is 50 EGP!", "Warning", JOptionPane.WARNING_MESSAGE);
                withdrawTextbox.setText("");
                break;
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton numPad0;
    private javax.swing.JButton numPad00;
    private javax.swing.JButton numPad000;
    private javax.swing.JButton numPad1;
    private javax.swing.JButton numPad2;
    private javax.swing.JButton numPad3;
    private javax.swing.JButton numPad4;
    private javax.swing.JButton numPad5;
    private javax.swing.JButton numPad6;
    private javax.swing.JButton numPad7;
    private javax.swing.JButton numPad8;
    private javax.swing.JButton numPad9;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField withdrawTextbox;
    // End of variables declaration//GEN-END:variables
}
